-- Highlight Keywords
highlight("function", "reserved")
highlight("param", "reserved")
highlight("if", "reserved")
highlight("elseif", "reserved")
highlight("else", "reserved")
highlight("switch", "reserved")
highlight("case", "reserved")
highlight("default", "reserved")
highlight("foreach", "reserved")
highlight("while", "reserved")
highlight("for", "reserved")
highlight("do", "reserved")
highlight("until", "reserved")
highlight("try", "reserved")
highlight("catch", "reserved")
highlight("finally", "reserved")
highlight("throw", "reserved")
highlight("return", "reserved")
highlight("break", "reserved")
highlight("continue", "reserved")
highlight("exit", "reserved")
highlight("filter", "reserved")
highlight("workflow", "reserved")
highlight("begin", "reserved")
highlight("process", "reserved")
highlight("end", "reserved")
highlight("dynamicparam", "reserved")
highlight("class", "reserved")
highlight("enum", "reserved")
highlight("trap", "reserved")
highlight("data", "reserved")
highlight("using", "reserved")
highlight("namespace", "reserved")
highlight("module", "reserved")
highlight("script", "reserved")

highlight("$null", "binary")
highlight("$true", "binary")
highlight("$false", "binary")
highlight("$PSVersionTable", "binary")
highlight("$?", "binary")
highlight("$PWD", "binary")
highlight("$HOME", "binary")

-- Common cmdlets
highlight("Get-Item", "function")
highlight("Set-Item", "function")
highlight("Get-Content", "function")
highlight("Set-Content", "function")
highlight("Add-Content", "function")
highlight("Get-ChildItem", "function")
highlight("Get-Process", "function")
highlight("Stop-Process", "function")
highlight("Start-Process", "function")
highlight("Get-Service", "function")
highlight("Start-Service", "function")
highlight("Stop-Service", "function")
highlight("Restart-Service", "function")
highlight("Get-Command", "function")
highlight("Get-Help", "function")
highlight("Write-Host", "function")
highlight("Write-Output", "function")
highlight("Write-Error", "function")
highlight("Write-Warning", "function")
highlight("Read-Host", "function")
highlight("New-Item", "function")
highlight("New-Object", "function")
highlight("New-PSDrive", "function")
highlight("Remove-Item", "function")
highlight("Remove-Process", "function")
highlight("Test-Path", "function")
highlight("Join-Path", "function")
highlight("Split-Path", "function")
highlight("Resolve-Path", "function")
highlight("Select-Object", "function")
highlight("Where-Object", "function")
highlight("Sort-Object", "function")
highlight("Group-Object", "function")
highlight("Measure-Object", "function")
highlight("ForEach-Object", "function")
highlight("Invoke-Command", "function")
highlight("Invoke-WebRequest", "function")
highlight("Invoke-Expression", "function")
highlight("Invoke-RestMethod", "function")
highlight("Invoke-Item", "function")
highlight("ConvertTo-Json", "function")
highlight("ConvertFrom-Json", "function")
highlight("ConvertTo-Csv", "function")
highlight("ConvertFrom-Csv", "function")
highlight("Export-Csv", "function")
highlight("Import-Csv", "function")
highlight("Import-Module", "function")
highlight("Export-ModuleMember", "function")
highlight("Start-Job", "function")
highlight("Get-Job", "function")
highlight("Receive-Job", "function")
highlight("Remove-Job", "function")
highlight("Wait-Job", "function")
highlight("Clear-Host", "function")
highlight("Get-Date", "function")
highlight("Set-Location", "function")
highlight("Set-Alias", "function")
highlight("Get-Alias", "function")
highlight("New-Alias", "function")
highlight("Copy-Item", "function")
highlight("Move-Item", "function")
highlight("Rename-Item", "function")
highlight("Test-Connection", "function")
highlight("Restart-Computer", "function")
highlight("Stop-Computer", "function")

-- Operators
highlight("=", "operator")
highlight("+=", "operator")
highlight("-=", "operator")
highlight("*=", "operator")
highlight("/=", "operator")
highlight("-eq", "operator")
highlight("-ne", "operator")
highlight("-gt", "operator")
highlight("-ge", "operator")
highlight("-lt", "operator")
highlight("-le", "operator")
highlight("-like", "operator")
highlight("-notlike", "operator")
highlight("-match", "operator")
highlight("-notmatch", "operator")
highlight("-contains", "operator")
highlight("-notcontains", "operator")
highlight("-in", "operator")
highlight("-notin", "operator")
highlight("-is", "operator")
highlight("-isnot", "operator")
highlight("-and", "operator")
highlight("-or", "operator")
highlight("-xor", "operator")
highlight("-not", "operator")
highlight("+", "operator")
highlight("-", "operator")
highlight("*", "operator")
highlight("/", "operator")
highlight("%", "operator")
highlight("++", "operator")
highlight("--", "operator")
highlight("&", "operator")
highlight("|", "operator")
highlight(">", "operator")
highlight(">>", "operator")
highlight(">>>", "operator")
highlight("::", "operator")
highlight(".", "operator")

-- Special Characters
highlight("{", "binary")
highlight("}", "binary")
highlight("[", "binary")
highlight("]", "binary")
highlight("(", "binary")
highlight(")", "binary")
highlight(";", "binary")
highlight(",", "binary")
highlight(":", "binary")
highlight("$", "binary")
highlight("?", "binary")

-- Strings
highlight_region("\"", "\"", "string")
highlight_region("'", "'", "string")
highlight_region("@\"", "\"@", "string")
highlight_region("@'", "'@", "string")

-- Comments
highlight_region("#", "", "comments", true)
highlight_region("<#", "#>", "comments", false)

-- Comments
add_comment("PowerShell: the language that only improves the shell it destroyed")
add_comment("Every cmdlet is one alias away from being cursed")
add_comment("The verbose flag is our cry for help")
add_comment("It's not Unix, it's a pipeline that eats Windows")
add_comment("Objects are passed, memory is lost")
add_comment("Get-Help positional-parameter-is-me")

-- Autocomplete

function detect_functions(content)
    local functionNames = {}

    for line in content:gmatch("[^\r\n]+") do
        local functionName = line:match("%s*function%s+([%w%-]+)")
        if not functionName then
            functionName = line:match("%s*(%a[%w%-]*)[\\:]:??")
        end
        if functionName then
            table.insert(functionNames, functionName)
        end
    end

    return functionNames
end

function detect_variables(content)
    local variable_names = {}
    local lines = content:gmatch("[^\r\n]+")

    for line in lines do
        local variable = line:match("%$([%w_]+)")
        if variable then
            table.insert(variable_names, variable)
        end
    end

    return variable_names
end