-- Highlight Keywords
highlight("@import", "reserved")
highlight("@use", "reserved")
highlight("@forward", "reserved")
highlight("@include", "reserved")
highlight("@mixin", "reserved")
highlight("@function", "reserved")
highlight("@extend", "reserved")
highlight("@each", "reserved")
highlight("@for", "reserved")
highlight("@while", "reserved")
highlight("@if", "reserved")
highlight("@else", "reserved")
highlight("@else if", "reserved")
highlight("@return", "reserved")
highlight("@media", "reserved")
highlight("@supports", "reserved")
highlight("@keyframes", "reserved")
highlight("@font-face", "reserved")
highlight("@page", "reserved")
highlight("@charset", "reserved")
highlight("@namespace", "reserved")
highlight("@debug", "reserved")
highlight("@warn", "reserved")
highlight("@error", "reserved")
highlight("@at-root", "reserved")

-- CSS properties
highlight("color", "member")
highlight("background", "member")
highlight("background-color", "member")
highlight("background-image", "member")
highlight("border", "member")
highlight("border-color", "member")
highlight("border-radius", "member")
highlight("margin", "member")
highlight("padding", "member")
highlight("width", "member")
highlight("height", "member")
highlight("min-width", "member")
highlight("max-width", "member")
highlight("min-height", "member")
highlight("max-height", "member")
highlight("font", "member")
highlight("font-size", "member")
highlight("font-weight", "member")
highlight("font-family", "member")
highlight("font-style", "member")
highlight("text-align", "member")
highlight("text-decoration", "member")
highlight("text-transform", "member")
highlight("display", "member")
highlight("position", "member")
highlight("top", "member")
highlight("bottom", "member")
highlight("left", "member")
highlight("right", "member")
highlight("z-index", "member")
highlight("flex", "member")
highlight("flex-direction", "member")
highlight("justify-content", "member")
highlight("align-items", "member")
highlight("align-self", "member")
highlight("gap", "member")
highlight("grid", "member")
highlight("grid-template-columns", "member")
highlight("grid-template-rows", "member")
highlight("overflow", "member")
highlight("overflow-x", "member")
highlight("overflow-y", "member")
highlight("opacity", "member")
highlight("transform", "member")
highlight("transition", "member")
highlight("animation", "member")
highlight("cursor", "member")
highlight("content", "member")
highlight("visibility", "member")
highlight("box-sizing", "member")
highlight("box-shadow", "member")
highlight("line-height", "member")
highlight("letter-spacing", "member")
highlight("white-space", "member")
highlight("vertical-align", "member")

-- Units
highlight("px", "symbol")
highlight("em", "symbol")
highlight("rem", "symbol")
highlight("vh", "symbol")
highlight("vw", "symbol")
highlight("vmin", "symbol")
highlight("vmax", "symbol")
highlight("%", "symbol")
highlight("deg", "symbol")
highlight("rad", "symbol")
highlight("s", "symbol")
highlight("ms", "symbol")
highlight("fr", "symbol")

-- Pseudo classes
highlight(":hover", "annotation")
highlight(":active", "annotation")
highlight(":focus", "annotation")
highlight(":visited", "annotation")
highlight(":first-child", "annotation")
highlight(":last-child", "annotation")
highlight(":nth-child", "annotation")
highlight(":before", "annotation")
highlight(":after", "annotation")
highlight("::before", "annotation")
highlight("::after", "annotation")
highlight("::placeholder", "annotation")
highlight(":root", "annotation")
highlight(":not", "annotation")

-- Values
highlight("none", "binary")
highlight("block", "binary")
highlight("inline", "binary")
highlight("inline-block", "binary")
highlight("flex", "binary")
highlight("grid", "binary")
highlight("absolute", "binary")
highlight("relative", "binary")
highlight("fixed", "binary")
highlight("sticky", "binary")
highlight("auto", "binary")
highlight("inherit", "binary")
highlight("initial", "binary")
highlight("unset", "binary")
highlight("important", "binary")
highlight("transparent", "binary")
highlight("bold", "binary")
highlight("italic", "binary")
highlight("underline", "binary")
highlight("center", "binary")
highlight("left", "binary")
highlight("right", "binary")
highlight("top", "binary")
highlight("bottom", "binary")
highlight("space-between", "binary")
highlight("space-around", "binary")
highlight("wrap", "binary")
highlight("nowrap", "binary")
highlight("hidden", "binary")
highlight("visible", "binary")
highlight("pointer", "binary")
highlight("default", "binary")

-- Operators
highlight("#", "operator")
highlight(".", "operator")
highlight("&", "operator")
highlight(">", "operator")
highlight("+", "operator")
highlight("~", "operator")
highlight("*", "operator")
highlight("=", "operator")

-- Special Characters
highlight("{", "binary")
highlight("}", "binary")
highlight("[", "binary")
highlight("]", "binary")
highlight("(", "binary")
highlight(")", "binary")
highlight(";", "binary")
highlight(",", "binary")
highlight(":", "binary")
highlight("!important", "binary")

-- Strings
highlight_region("\"", "\"", "string")
highlight_region("'", "'", "string")

-- Comments
highlight_region("//", "", "comments", true)
highlight_region("/*", "*/", "comments", false)

-- Comments
add_comment("SCSS: CSS with superpowers and nested regrets")
add_comment("You will spend 6 hours fighting vertical centering")
add_comment("!important is a cry for help")
add_comment("The specificity wars never end")
add_comment("Mixin? More like mix-you-in-problems")
add_comment("It's not a bug, it's responsive design")

-- Autocomplete

function detect_functions(content)
    local functionNames = {}
    return functionNames
end

function detect_variables(content)
    local variable_names = {}
    local lines = content:gmatch("[^\r\n]+")

    for line in lines do
        local variable = line:match("%s*%$([%w_]+)%s*:")
        if variable then
            table.insert(variable_names, variable)
        end
    end

    return variable_names
end